name: bottle-deps
on: push

jobs:
  bottle-dependencies:
    runs-on: macos-26

    env:
      HOMEBREW_NO_INSTALL_FROM_API: 1
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Build bottles
        run: |
          brew tap Macaulay2/tap
          brew install --verbose --build-bottle dtorrance/tap/normaliz

      - uses: actions/upload-artifact@v4
        with:
          path: |
            *.bottle.tar.gz
